//Types for Authentication
export const CREATE_NEW_ACCOUNT = 'CREATE_NEW_ACCOUNT'
export const LOG_INTO_ACCOUNT = 'LOG_INTO_ACCOUNT'
export const LOG_OFF_ACCOUNT = 'LOG_OFF_ACCOUNT'
export const ERROR_WHEN_LOGGING = 'ERROR_WHEN_LOGGING'
export const ERROR_WHEN_CREATING_ACCOUNT = 'ERROR_WHEN_CREATING_ACCOUNT'

//Types for Despesas
//CREATE
export const CREATE_DESPESA = 'CREATE_DESPESA'
export const RESET_CREATE_DESPESA = 'RESET_CREATE_DESPESA'
//READ
export const READ_DESPESAS = 'READ_DESPESAS'
//UPDATE
export const START_DESPESA_UPDATE = 'START_DESPESA_UPDATE'
export const UPDATE_DESPESA = 'UPDATE_DESPESA'
export const RESET_UPDATE_DESPESA = 'RESET_UPDATE_DESPESA'
//DELETE
export const DELETE_DESPESA = 'DELETE_DESPESA'
export const RESET_DELETE_DESPESA = 'RESET_DELETE_DESPESA'

//Types for Receitas
//CREATE
export const CREATE_RECEITA = 'CREATE_RECEITA'
export const RESET_CREATE_RECEITA = 'RESET_CREATE_RECEITA'
//READ
export const READ_RECEITAS = 'READ_RECEITAS'
//UPDATE
export const START_RECEITA_UPDATE = 'START_RECEITA_UPDATE'
export const UPDATE_RECEITA = 'UPDATE_RECEITA'
export const RESET_UPDATE_RECEITA = 'RESET_UPDATE_RECEITA'
//DELETE
export const DELETE_RECEITA = 'DELETE_RECEITA'
export const RESET_DELETE_RECEITA = 'RESET_DELETE_RECEITA'
